### ISSUE TITLE
Some documentation?

### ISSUE THREAD

**Issue by madaolex** [terdelyi/omnipay-perfectmoney#1]
Hi!

Can you add at least basics in documentation?
I can compare your code with other omnipay modules, but it will be better if you will write how to work with your module :)

**Comment by madaolex** [comment]
And another question:
Will yo work on this module or not anymore?

**Comment by terdelyi** [comment]
Hi @MADAOLEX,

In case if you're still interested to know my answers this package is not actively maintained, but it's only because I don't have a working test user for Perfect Money anymore. The usage is 100% compatible with Omnipay v2: https://omnipay.thephpleague.com/api/authorizing/, everything else could be peek out from the source code (`setAccount`, `setAccountName`, `setPassphrase`), it's not a long read.

**Comment by madaolex** [comment]
Hi @terdelyi!

Thanks for your answer. After some search I found this https://github.com/aleksandrzhiliaev/omnipay-perfectmoney
He forked your module and some others that I need and led them to one same style. In case of my limited time this comes very handy :D 
Maybe someday I will fork your module too and update it to Omnipay v3. So thank you for your omnipay-perfectmoney.

**Comment by madaolex** [comment]
Hi again @terdelyi,

I suppose there is no way to do withdrawal through Omnipay?

**Comment by terdelyi** [comment]
Meanwhile Omnipay supports refund (https://omnipay.thephpleague.com/api/refunds/) at the time when I was creating this package Perfect Money didn't have the option to do refunds. But you can fork this or the other repo you've mentioned and could implement the solution anytime.

**Comment by madaolex** [comment]
Refund != withdrawal. Refund works with already processed transactions, whereas I need simple money transfer from my account to another via Perfect Money API. Unfortunatelly Omnipay does not supports this.

**Comment by terdelyi** [comment]
You're right: Omnipay is a payment processing library and not a Perfect Money API package to moving your money between accounts. It's primary purpose to make payments platform independent through gateways.

**Comment by madaolex** [comment]
I know but It's not only me wants such a feature :)
https://github.com/thephpleague/omnipay/issues/244
